name: geek_code
version: 2.0.1
author: Meshulam Silk <moomoohk@ymail.com>
description: Dart implementation of The Geek Code
homepage: http://moomoohk.github.io/projects/geek_code
documentation: http://moomoohk.github.io/docs/dart/geek_code
dev_dependencies:
  unittest: any
